[formatter.alejandra]
command = "alejandra"
options = ["--config", "./alejandra.toml"]
includes = ["*.nix"]
excludes = [
    "hosts/*/hardware-configuration.nix",
    "*.lock"
]

[formatter.statix]
command = "statix"
options = ["fix"]
includes = ["*.nix"]
excludes = [
    "hosts/*/hardware-configuration.nix",
    "*.lock"
]
