#!/usr/bin/env bash
# Interactive wizard: pick flake inputs, update them, and open a PR.
# Run with `nix run .#update-inputs` or pass input names to skip the prompt.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

default_inputs="llm-agents,agent-toolkit,t3code,mail-bean"

if [[ -n $(git status --porcelain --untracked-files=no) ]]; then
  echo "error: working tree has uncommitted changes" >&2
  exit 1
fi

mapfile -t available < <(nix flake metadata --json | jq -r '.locks.nodes.root.inputs | keys[]')

if (($# > 0)); then
  picks=("$@")
  for pick in "${picks[@]}"; do
    if ! printf '%s\n' "${available[@]}" | grep -qx "$pick"; then
      echo "error: unknown flake input '$pick'" >&2
      exit 1
    fi
  done
else
  if ! command -v gum >/dev/null; then
    echo "error: gum not found; run via 'nix run .#update-inputs' or pass input names as arguments" >&2
    exit 1
  fi
  mapfile -t picks < <(gum choose --no-limit --header "Inputs to update" --selected "$default_inputs" "${available[@]}")
fi

if ((${#picks[@]} == 0)); then
  echo "nothing selected" >&2
  exit 1
fi

branch="chore/update-$(IFS=-; echo "${picks[*]}")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

git fetch origin main
git switch -c "$branch" origin/main
cp flake.lock "$tmp/flake.lock.before"

nix flake update "${picks[@]}" 2>&1 | tee "$tmp/nix-output.txt"

if git diff --quiet flake.lock; then
  echo "flake.lock unchanged, nothing to do"
  git switch -
  git branch -D "$branch"
  exit 0
fi

joined=$(printf '%s, ' "${picks[@]}")
title="chore: update ${joined%, }"

git commit -m "$title" flake.lock

FLAKE_UPDATE_INTRO="Manual update of \`flake.lock\` for ${joined%, }." \
FLAKE_UPDATE_FOOTER="This PR was generated by \`scripts/update-inputs.sh\`." \
  node .github/scripts/generate-flake-update-body.mjs \
  "$tmp/flake.lock.before" flake.lock "$tmp/pr-body.md" "$tmp/nix-output.txt"

git push -u origin "$branch"
gh pr create --title "$title" --body-file "$tmp/pr-body.md" --base main
